# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Zalo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zalo
  pod 'Alamofire'
  pod 'Socket.IO-Client-Swift'
  target 'ZaloTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZaloUITests' do
    # Pods for testing
  end

end
